apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kong-proxy-pod-kill
  annotations:
    argocd.argoproj.io/sync-wave: "90"
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      chaos-target: kong-proxy
  duration: "20s"
  gracePeriod: 5
