apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  JWT_SECRET: change-me
  MONGO_URI: mongodb://mongo-mongodb-sharded-mongos:27017/openleaf_db?replicaSet=rsShard0
  STRIPE_SECRET: sk_test_replace_me
  STRIPE_WEBHOOK_SECRET: whsec_replace_me
  STRIPE_PRICE_BASIC: price_replace_basic
  STRIPE_PRICE_PREMIUM: price_replace_premium
