apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: kong-prometheus-global
  annotations:
    argocd.argoproj.io/sync-wave: "10"
plugin: prometheus
config:
  per_consumer: false
  status_code_metrics: true
  latency_metrics: true
  bandwidth_metrics: true
  upstream_health_metrics: true
