apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: kong-proxy-stress
spec:
  mode: one
  selector:
    labelSelectors:
      chaos-target: kong-proxy
  stressors:
    cpu:
      workers: 2
      load: 90
    memory:
      workers: 1
      size: "800MB"
  duration: "45s"
