apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: analytics-network-delay
spec:
  action: delay
  mode: all
  selector:
    labelSelectors:
      app: analytics-service
  delay:
    latency: "500ms"
    correlation: "100"
    jitter: "50ms"
  duration: "2m"
  direction: to
