apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: payment-pod-failure
  annotations:
    argocd.argoproj.io/sync-wave: "90"
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      app: payment-service
  duration: "30s"
  gracePeriod: 0
  scheduler:
    cron: "@every 5m"
