name: CI/CD

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  openleaf-ci:
    uses: temitayocharles/shared-workflows/.github/workflows/openleaf-ci.yml@main
    with:
      image_owner: ${{ github.repository_owner }}
      run_trivy: true
    secrets: inherit
